name: Expo CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - uses: bycedric/expo-github-action-concept@master
        with:
          version: latest
          username: bycedric
          password: ${secrets.password}
      - run: expo --version
